openapi: 3.0.0
info:
  title: API - Orders Clean Project
  version: 1.0.0
servers:
  - url: 'http://localhost:4002'
tags:
  - name: Product
paths:
  /api/product:
    post:
      tags:
        - Product
      summary: createProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Refrigerante
                description: Refrigerante
                price: 8
                stock: 50
                category: 3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Product
      summary: getAllProducts
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/product/3:
    patch:
      tags:
        - Product
      summary: pathProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Hamburguer
                description: Hamburguer
                category: 1
                stock: 20
                price: 30
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/product/2:
    delete:
      tags:
        - Product
      summary: deleteProduct
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/product/1:
    get:
      tags:
        - Product
      summary: getProductsById
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/product/filters:
    get:
      tags:
        - Product
      summary: getProductByFilter
      parameters:
        - name: category
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
