apiVersion: v1
kind: Service
metadata:
  name: ms-product-service
  namespace: default
  labels:
    name: ms-product
    app: service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 4002
    targetPort: 4002
  externalIPs:
  - 192.168.49.2
  selector:
    app: ms-product
